version: "3.8"
services:

  consul:
    image: consul:latest
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect=1 -ui -client 0.0.0.0"


  servicea:
    container_name: servicea
    restart: always
    build: servicea
    ports: 
      - "5000:3000"

    volumes:
      - .:/usr/src/servicea

  serviceb:
    container_name: serviceb
    restart: always
    build: serviceb
    ports: 
      - "5001:3000"
    volumes:
      - .:/usr/src/serviceb


  servicec:
    container_name: servicec
    restart: always
    build: servicec
    ports: 
      - "5002:3000"
    volumes:
      - .:/usr/src/servicec

  
  
