version: "3.8"
services:

  servicea:
    container_name: servicea
    restart: always
    build: servicea
    ports: 
      - "5000:3000"

    volumes:
      - .:/usr/src/servicea

  serviceb:
    container_name: serviceb
    restart: always
    build: serviceb
    ports: 
      - "5001:3000"
    volumes:
      - .:/usr/src/serviceb


  servicec:
    container_name: servicec
    restart: always
    build: servicec
    ports: 
      - "5002:3000"
    volumes:
      - .:/usr/src/servicec

  
  
